description = "`#[derive(FromRequest)]` generates a request-scoped constructor with the expected signature."

[expectations]
codegen = "pass"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
