[package]
name = "postgres_sessions"
version = "0.1.0"
edition.workspace = true

[dependencies]
pavex.workspace = true
pavex_session.workspace = true
pavex_session_sqlx = { workspace = true, features = ["postgres"] }
pavex_cli_client.workspace = true
serde.workspace = true
cargo_px_env.workspace = true
tokio.workspace = true
anyhow.workspace = true
sqlx.workspace = true
