version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: test-pavex-session-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: session_test
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d session_test -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: test-pavex-session-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: session_test
    ports:
      - "53306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  default:
    name: test-databases
