[template]
cargo_generate_version = ">=0.18.0"
ignore = ["target/", "Cargo.lock"]

[placeholders.pavex_package_spec]
type = "string"
prompt = "What version of `pavex` do you want to use?"

[placeholders.pavex_cli_client_package_spec]
type = "string"
prompt = "What version of `pavex_cli_client` do you want to use?"