[package]
name = "post"
version = "0.1.0"
edition.workspace = true

[dependencies]
pavex = { workspace = true }
pavex_cli_client = { workspace = true }
pavex_tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
cargo_px_env = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["time"] }
