[graph]
all-features = true
no-default-features = false

[advisories]
ignore = [
    # `instant` crate is unmaintained, but we depend on it transitively,
    # so no easy way to remove it until all intermediate crates get rid of it.
    # Since it isn't vulnerable, we'll ignore the advisory for now.
    "RUSTSEC-2024-0384",
    # `paste` is unmaintained, but it's a small utility for macro-writing.
    # There are no known vulnerabilities, so we'll ignore the advisory for now.
    "RUSTSEC-2024-0436",
    # `rsa` crate has a timing sidechannel vulnerability (Marvin Attack)
    # but it's a transitive dependency through sqlx-mysql and no safe upgrade
    # is available. The risk is acceptable for server-side usage where timing
    # attacks are difficult to execute.
    "RUSTSEC-2023-0071",
]

[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "OpenSSL",
    "Zlib",
    "CDLA-Permissive-2.0",
]
unused-allowed-license = "allow"
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false

[bans]
deny = ["openssl", "openssl-sys"]
