[package]
name = "application"
edition = "2021"
version = "0.1.0"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies.app_blueprint]
version = "0.1.0"
path = "../app_blueprint"
package = "app_blueprint"

[dependencies.bytes]
version = "1.4.0"
package = "bytes"

[dependencies.http]
version = "0.2.9"
package = "http"

[dependencies.http_body]
version = "0.4.5"
package = "http-body"

[dependencies.hyper]
version = "0.14.26"
package = "hyper"

[dependencies.pavex_runtime]
version = "0.1.0"
path = "../../../libs/pavex_runtime"
package = "pavex_runtime"
