[package]
name = "app_server_sdk"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "bp"

[dependencies]
http = { version = "0.2.9", package = "http" }
hyper = { version = "0.14.26", package = "hyper" }
pavex_runtime = { version = "0.1.0", path = "../../../libs/pavex_runtime", package = "pavex_runtime" }
