[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[dependencies]
# Telemetry
tracing = "0.1"
tracing-bunyan-formatter = "0.3"
tracing_log_error = { version = "0.1" }
tracing-panic = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "registry",
    "smallvec",
    "std",
    "tracing-log",
] }

# Configuration
dotenvy = "0.15"

anyhow = "1"
pavex = { version = "0.1.80" }
tokio = { version = "1", features = ["full"] }
server_sdk = { path = "../server_sdk" }
app = { path = "../app" }
workspace_hack = { path = "../workspace_hack" }

[dev-dependencies]
reqwest = "0.12"
