[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[[bin]]
path = "src/bin/bp.rs"
name = "bp"

[lints.rust]
# `pavex_ide_hint` is used in Pavex's `f!` macro to "nudge" the IDE
# and force it to provide completions and "go-to-definition" correctly
# for the paths passed to the `f!` macro.
# It must be allowed in all local crates that use `f!`.
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(pavex_ide_hint)'] }

[dependencies]
anyhow = "1"
pavex_cli_client = "0.1"
cargo_px_env = "0.1"
pavex = "0.1"
pavex_tracing = "0.1"

sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "migrate",
    "uuid",
    "macros",
    "time",
    "postgres",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
secrecy = { version = "0.8", features = ["serde"] }
tokio = { version = "1", features = ["rt"] }
uuid = { version = "1", features = ["serde", "v4"] }

# Passwords
rand = { version = "0.8", features = ["std_rng"] }
argon2 = { version = "0.5", features = ["std"] }

# JWTs
jsonwebtoken = "8"

# Configuration
serde-aux = "4"

workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
jwt-simple = "0.11"
