[package]
name = "dep_29415e1g"
version = "0.1.0"
edition.workspace = true

[lints.rust.unused]
level = "allow"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../../workspace_hack" }
