[package]
name = "pxh"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
fs-err = "2.11.0"
anyhow = "1.0.75"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.27"
camino = { version = "1", features = ["serde1"] }
globwalk = "0.9.0"
regex = "1"
similar = { version = "2.3", features = ["inline"] }
console = "0.15.1"
pathdiff = "0.2.1"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
