//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: Router,
    application_state: ApplicationState,
}
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ApplicationConfig {
    #[serde(default)]
    pub cookies: biscotti::ProcessorConfig,
    pub session: pavex_session::SessionConfig,
}
pub struct ApplicationState {
    pub processor: biscotti::Processor,
    pub session_config: pavex_session::SessionConfig,
    pub session_store: pavex_session::SessionStore,
}
impl ApplicationState {
    pub async fn new(
        app_config: crate::ApplicationConfig,
    ) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
        Ok(Self::_new(app_config.session, app_config.cookies).await)
    }
    async fn _new(
        v0: pavex_session::SessionConfig,
        v1: biscotti::ProcessorConfig,
    ) -> crate::ApplicationState {
        let v2 = pavex_session_memory_store::InMemorySessionStore::new();
        let v3 = <pavex_session::SessionStore as core::convert::From<
            pavex_session_memory_store::InMemorySessionStore,
        >>::from(v2);
        let v4 = pavex::cookie::config_into_processor(v1);
        crate::ApplicationState {
            processor: v4,
            session_config: v0,
            session_store: v3,
        }
    }
}
#[deprecated(note = "Use `ApplicationState::new` instead.")]
pub async fn build_application_state(
    app_config: crate::ApplicationConfig,
) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
    crate::ApplicationState::new(app_config).await
}
#[derive(Debug, thiserror::Error)]
pub enum ApplicationStateError {}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    async fn handler(
        request: http::Request<hyper::body::Incoming>,
        connection_info: Option<pavex::connection::ConnectionInfo>,
        server_state: std::sync::Arc<ServerState>,
    ) -> pavex::response::Response {
        let (router, state) = (&server_state.router, &server_state.application_state);
        router.route(request, connection_info, state).await
    }
    let router = Router::new();
    let server_state = std::sync::Arc::new(ServerState {
        router,
        application_state,
    });
    server_builder.serve(handler, server_state)
}
struct Router {
    router: matchit::Router<u32>,
}
impl Router {
    /// Create a new router instance.
    ///
    /// This method is invoked once, when the server starts.
    pub fn new() -> Self {
        Self { router: Self::router() }
    }
    fn router() -> matchit::Router<u32> {
        let router = matchit::Router::new();
        router
    }
    pub async fn route(
        &self,
        request: http::Request<hyper::body::Incoming>,
        _connection_info: Option<pavex::connection::ConnectionInfo>,
        #[allow(unused)]
        state: &ApplicationState,
    ) -> pavex::response::Response {
        let (request_head, _) = request.into_parts();
        let request_head: pavex::request::RequestHead = request_head.into();
        let Ok(matched_route) = self.router.at(&request_head.target.path()) else {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            return route_0::entrypoint(
                    &state.processor,
                    &request_head,
                    &state.session_config,
                    &state.session_store,
                    &allowed_methods,
                )
                .await;
        };
        match matched_route.value {
            i => unreachable!("Unknown route id: {}", i),
        }
    }
}
pub mod route_0 {
    pub async fn entrypoint<'a, 'b, 'c, 'd, 'e>(
        s_0: &'a biscotti::Processor,
        s_1: &'b pavex::request::RequestHead,
        s_2: &'c pavex_session::SessionConfig,
        s_3: &'d pavex_session::SessionStore,
        s_4: &'e pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c, 'd, 'e>(
        mut s_0: pavex::cookie::ResponseCookies,
        s_1: &'a biscotti::Processor,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c pavex_session::SessionConfig,
        s_4: &'d pavex_session::SessionStore,
        s_5: &'e pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = handler(s_5).await;
        let response = post_processing_0(s_2, s_1, response, s_3, s_4, &mut s_0).await;
        let response = post_processing_1(response, s_0, s_1).await;
        response
    }
    async fn wrapping_0(
        v0: &biscotti::Processor,
        v1: &pavex::request::RequestHead,
        v2: &pavex_session::SessionConfig,
        v3: &pavex_session::SessionStore,
        v4: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v5 = pavex::cookie::ResponseCookies::new();
        let v6 = crate::route_0::Next0 {
            s_0: v5,
            s_1: v0,
            s_2: v1,
            s_3: v2,
            s_4: v3,
            s_5: v4,
            next: stage_1,
        };
        let v7 = pavex::middleware::Next::new(v6);
        let v8 = pavex::middleware::wrap_noop(v7).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v8)
    }
    async fn handler(v0: &pavex::router::AllowedMethods) -> pavex::response::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v1)
    }
    async fn post_processing_0(
        v0: &pavex::request::RequestHead,
        v1: &biscotti::Processor,
        v2: pavex::response::Response,
        v3: &pavex_session::SessionConfig,
        v4: &pavex_session::SessionStore,
        v5: &mut pavex::cookie::ResponseCookies,
    ) -> pavex::response::Response {
        let v6 = pavex::cookie::extract_request_cookies(v0, v1);
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::cookie::errors::ExtractRequestCookiesError::into_response(
                        &v7,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v8,
                    )
                };
            }
        };
        let v8 = pavex_session::SessionConfig::cookie_config(v3);
        let v9 = pavex_session::IncomingSession::extract(&v7, v8);
        let v10 = pavex_session::Session::new(v4, v3, v9);
        let v11 = pavex_session::finalize_session(v2, v5, v10).await;
        let v12 = match v11 {
            Ok(ok) => ok,
            Err(v12) => {
                return {
                    let v13 = pavex_session::errors::FinalizeError::into_response(&v12);
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v13,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v12)
    }
    async fn post_processing_1(
        v0: pavex::response::Response,
        v1: pavex::cookie::ResponseCookies,
        v2: &biscotti::Processor,
    ) -> pavex::response::Response {
        let v3 = pavex::cookie::inject_response_cookies(v0, v1, v2);
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::cookie::errors::InjectResponseCookiesError::into_response(
                        &v4,
                    );
                    <pavex::response::Response as pavex::response::IntoResponse>::into_response(
                        v5,
                    )
                };
            }
        };
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v4)
    }
    struct Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::cookie::ResponseCookies,
        s_1: &'a biscotti::Processor,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c pavex_session::SessionConfig,
        s_4: &'d pavex_session::SessionStore,
        s_5: &'e pavex::router::AllowedMethods,
        next: fn(
            pavex::cookie::ResponseCookies,
            &'a biscotti::Processor,
            &'b pavex::request::RequestHead,
            &'c pavex_session::SessionConfig,
            &'d pavex_session::SessionStore,
            &'e pavex::router::AllowedMethods,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, T> std::future::IntoFuture for Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4, self.s_5)
        }
    }
}
