//! This module encapsulates the logic required to compute, retrieve and analyse the
//! JSON crate documentation generated by `rustdoc`.
//!
//! [`CrateCollection`] is the key entrypoint.
use guppy::PackageId;
use once_cell::sync::Lazy;
pub use rustdoc_cache::{
    ALLOC_PACKAGE_ID_REPR, CORE_PACKAGE_ID_REPR, STD_PACKAGE_ID_REPR, TOOLCHAIN_CRATES,
};

pub(crate) use annotations::{AnnotatedItem, AnnotationCoordinates, ImplInfo};
pub use queries::{Crate, CrateCollection, CrateRegistry, GlobalItemId, ResolvedItem};
pub use rustdoc_cache::CannotGetCrateData;

mod annotations;
mod compute;
mod progress_reporter;
mod queries;

pub static STD_PACKAGE_ID: Lazy<PackageId> = Lazy::new(|| PackageId::new(STD_PACKAGE_ID_REPR));
pub static CORE_PACKAGE_ID: Lazy<PackageId> = Lazy::new(|| PackageId::new(CORE_PACKAGE_ID_REPR));
pub static ALLOC_PACKAGE_ID: Lazy<PackageId> = Lazy::new(|| PackageId::new(ALLOC_PACKAGE_ID_REPR));
