[package]
name = "error_observers"
version = "0.1.0"
edition = "2021"

[dependencies]
pavex.workspace = true
pavex_cli_client.workspace = true
serde.workspace = true
cargo_px_env.workspace = true
tracing.workspace = true
tracing_log_error.workspace = true
tokio.workspace = true
anyhow.workspace = true
workspace_hack = { version = "0.1", path = "../../workspace_hack" }
