[package]
name = "api_server_sdk"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "bp"

[dependencies]
bytes = { version = "1.4.0", package = "bytes" }
conduit_core = { version = "0.1.0", path = "../conduit_core", package = "conduit_core" }
http = { version = "1.0.0", package = "http" }
http_body_util = { version = "0.1.0", package = "http-body-util" }
hyper = { version = "1.0.0", package = "hyper" }
jsonwebtoken = { version = "8.3.0", package = "jsonwebtoken" }
pavex = { version = "0.1.0", path = "../../../libs/pavex", package = "pavex" }
sqlx_core = { version = "0.7.1", package = "sqlx-core" }
sqlx_postgres = { version = "0.7.1", package = "sqlx-postgres" }
thiserror = { version = "1.0.47", package = "thiserror" }
