[package]
name = "api_server_sdk"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "bp"

[dependencies]
bytes = { version = "1.4.0", package = "bytes" }
conduit_core = { version = "0.1.0", path = "../conduit_core", package = "conduit_core" }
http = { version = "0.2.9", package = "http" }
http_body = { version = "0.4.5", package = "http-body" }
hyper = { version = "0.14.26", package = "hyper" }
jsonwebtoken = { version = "8.3.0", package = "jsonwebtoken" }
pavex = { version = "0.1.0", path = "../../../libs/pavex", package = "pavex" }
sqlx_core = { version = "0.7.0-alpha.3", package = "sqlx-core" }
sqlx_postgres = { version = "0.7.0-alpha.3", package = "sqlx-postgres" }
thiserror = { version = "1.0.40", package = "thiserror" }
