[package]
name = "api_server_sdk"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "bp"

[dependencies]
conduit_core = { version = "0.1.0", path = "../conduit_core", package = "conduit_core" }
http = { version = "1.0.0", package = "http" }
hyper = { version = "1.1.0", package = "hyper" }
jsonwebtoken = { version = "8.3.0", package = "jsonwebtoken" }
matchit = { version = "0.7.3", git = "https://github.com/ibraheemdev/matchit", branch = "master", package = "matchit" }
pavex = { version = "0.1.0", path = "../../../libs/pavex", package = "pavex" }
sqlx_core = { version = "0.7.3", package = "sqlx-core" }
sqlx_postgres = { version = "0.7.3", package = "sqlx-postgres" }
thiserror = { version = "1.0.56", package = "thiserror" }
