//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: Router,
    application_state: ApplicationState,
}
pub struct ApplicationState {
    pub app_255_f_0769_a_singleton: app::a::Singleton,
    pub app_255_f_0769_singleton: app::Singleton,
    pub generic_string: app::Generic<alloc::string::String>,
    pub generic_u64_: app::Generic<u64>,
    pub type_: app::Type,
}
pub async fn build_application_state() -> crate::ApplicationState {
    let v0 = app::Type::new();
    let v1 = app::Generic::new();
    let v2 = app::Generic::new();
    let v3 = app::Singleton::new();
    let v4 = app::a::Singleton::new();
    crate::ApplicationState {
        app_255_f_0769_a_singleton: v4,
        app_255_f_0769_singleton: v3,
        generic_string: v2,
        generic_u64_: v1,
        type_: v0,
    }
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    async fn handler(
        request: http::Request<hyper::body::Incoming>,
        connection_info: Option<pavex::connection::ConnectionInfo>,
        server_state: std::sync::Arc<ServerState>,
    ) -> pavex::response::Response {
        let (router, state) = (&server_state.router, &server_state.application_state);
        router.route(request, connection_info, state).await
    }
    let router = Router::new();
    let server_state = std::sync::Arc::new(ServerState {
        router,
        application_state,
    });
    server_builder.serve(handler, server_state)
}
struct Router {
    router: matchit::Router<u32>,
}
impl Router {
    /// Create a new router instance.
    ///
    /// This method is invoked once, when the server starts.
    pub fn new() -> Self {
        Self { router: Self::router() }
    }
    fn router() -> matchit::Router<u32> {
        let mut router = matchit::Router::new();
        router.insert("/", 0u32).unwrap();
        router
    }
    pub async fn route(
        &self,
        request: http::Request<hyper::body::Incoming>,
        _connection_info: Option<pavex::connection::ConnectionInfo>,
        #[allow(unused)]
        state: &ApplicationState,
    ) -> pavex::response::Response {
        let (request_head, _) = request.into_parts();
        let request_head: pavex::request::RequestHead = request_head.into();
        let Ok(matched_route) = self.router.at(&request_head.target.path()) else {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            return route_1::entrypoint(&allowed_methods).await;
        };
        match matched_route.value {
            0u32 => {
                match &request_head.method {
                    &pavex::http::Method::GET => {
                        route_0::entrypoint(
                                &state.generic_u64_,
                                &state.app_255_f_0769_singleton,
                                &state.app_255_f_0769_a_singleton,
                                &state.type_,
                                &state.generic_string,
                            )
                            .await
                    }
                    _ => {
                        let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                                pavex::http::Method::GET,
                            ])
                            .into();
                        route_1::entrypoint(&allowed_methods).await
                    }
                }
            }
            i => unreachable!("Unknown route id: {}", i),
        }
    }
}
pub mod route_0 {
    pub async fn entrypoint<'a, 'b, 'c, 'd, 'e>(
        s_0: &'a app::Generic<u64>,
        s_1: &'b app::Singleton,
        s_2: &'c app::a::Singleton,
        s_3: &'d app::Type,
        s_4: &'e app::Generic<alloc::string::String>,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c, 'd, 'e>(
        s_0: &'a app::Generic<alloc::string::String>,
        s_1: &'b app::Generic<u64>,
        s_2: &'c app::Singleton,
        s_3: &'d app::a::Singleton,
        s_4: &'e app::Type,
    ) -> pavex::response::Response {
        let response = handler(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn wrapping_0(
        v0: &app::Generic<u64>,
        v1: &app::Singleton,
        v2: &app::a::Singleton,
        v3: &app::Type,
        v4: &app::Generic<alloc::string::String>,
    ) -> pavex::response::Response {
        let v5 = crate::route_0::Next0 {
            s_0: v4,
            s_1: v0,
            s_2: v1,
            s_3: v2,
            s_4: v3,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v7)
    }
    async fn handler(
        v0: &app::Generic<alloc::string::String>,
        v1: &app::Generic<u64>,
        v2: &app::Singleton,
        v3: &app::a::Singleton,
        v4: &app::Type,
    ) -> pavex::response::Response {
        let v5 = app::handler(v4, v0, v1, v2, v3);
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v5)
    }
    struct Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a app::Generic<alloc::string::String>,
        s_1: &'b app::Generic<u64>,
        s_2: &'c app::Singleton,
        s_3: &'d app::a::Singleton,
        s_4: &'e app::Type,
        next: fn(
            &'a app::Generic<alloc::string::String>,
            &'b app::Generic<u64>,
            &'c app::Singleton,
            &'d app::a::Singleton,
            &'e app::Type,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, 'e, T> std::future::IntoFuture for Next0<'a, 'b, 'c, 'd, 'e, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
pub mod route_1 {
    pub async fn entrypoint<'a>(
        s_0: &'a pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = wrapping_0(s_0).await;
        response
    }
    async fn stage_1<'a>(
        s_0: &'a pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let response = handler(s_0).await;
        response
    }
    async fn wrapping_0(
        v0: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v1 = crate::route_1::Next0 {
            s_0: v0,
            next: stage_1,
        };
        let v2 = pavex::middleware::Next::new(v1);
        let v3 = pavex::middleware::wrap_noop(v2).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v3)
    }
    async fn handler(v0: &pavex::router::AllowedMethods) -> pavex::response::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v1)
    }
    struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::router::AllowedMethods,
        next: fn(&'a pavex::router::AllowedMethods) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}