//! This crate encapsulates the logic required to cache and retrieve JSON documentation
//! generated by `rustdoc` for crates in a Pavex project's dependency graph.
//!
//! The cache is stored in a SQLite database at `~/.pavex/rustdoc/cache/{fingerprint}.db`.

pub mod annotations;
mod cache;
mod checksum;
mod format;
mod toolchain;
mod types;

pub use annotations::{AnnotatedItem, AnnotatedItems, IdConflict, ImplInfo};
pub use cache::{
    ProcessedCacheEntry, HydratedCacheEntry, RustdocCacheKey, RustdocGlobalFsCache,
    cargo_fingerprint,
};
pub use checksum::checksum_crate;
pub use format::check_format;
pub use toolchain::get_toolchain_crate_docs;
pub use types::*;

/// Crate version - used as part of cache fingerprint.
pub const CRATE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Standard library crate package ID representation.
pub const STD_PACKAGE_ID_REPR: &str = "std";
/// Core crate package ID representation.
pub const CORE_PACKAGE_ID_REPR: &str = "core";
/// Alloc crate package ID representation.
pub const ALLOC_PACKAGE_ID_REPR: &str = "alloc";

/// The set of toolchain crates that are bundled with Rust.
pub const TOOLCHAIN_CRATES: [&str; 3] = [
    STD_PACKAGE_ID_REPR,
    CORE_PACKAGE_ID_REPR,
    ALLOC_PACKAGE_ID_REPR,
];

/// Return the options to pass to `rustdoc` in order to generate JSON documentation.
///
/// We isolate this logic in a separate function in order to be able to refer to these
/// options from various places in the codebase and maintain a single source of truth.
///
/// In particular, they do affect our caching logic (see the `cache` module).
pub fn rustdoc_options() -> [&'static str; 4] {
    [
        "--document-private-items",
        "-Zunstable-options",
        "-wjson",
        "--document-hidden-items",
    ]
}
