[package]
name = "configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
pavex = { path = "../../../../libs/pavex" }
pavex_cli_client = { path = "../../../../libs/pavex_cli_client" }
cargo_px_env = "0.1"
serde = { version = "1.0", features = ["derive"] }
secrecy = { version = "0.8", features = ["serde"] }

[workspace]
members = [".", "server_sdk"]
