[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin/api.rs"
name = "api"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
api_server_sdk = { path = "../api_server_sdk" }
hyper = "0.14"

# Configuration
figment = { version = "0.10", features = ["env", "yaml"] }
serde = { version = "1", features = ["derive"]}

# Telemetry
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "smallvec", "std", "registry"] }
tracing-log = "0.1"
tracing-bunyan-formatter = "0.3"