all-features = true

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
# Add a CVE to this list to "silence" it in CI
ignore = []