[package]
name = "user_middleware"
version = "0.1.0"
edition.workspace = true

[dependencies]
pavex = { workspace = true }
pavex_cli_client = { workspace = true }
cargo_px_env = { workspace = true }
workspace_hack = { version = "0.1", path = "../../workspace_hack" }
