[package]
name = "app_e4a8214b"
version = "0.1.0"
edition.workspace = true

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = ["cfg(pavex_ide_hint)"]

[dependencies]
workspace_hack = { version = "0.1", path = "../../../workspace_hack" }

[dependencies.pavex]
workspace = true

[dependencies.pavex_cli_client]
workspace = true

[dependencies.dep]
path = "ephemeral_deps/dep"
package = "dep_29415e1g"
