name: 'Create check'
description: 'Create a check on a PR'
inputs:
  pr_number:
    description: 'The number of the PR'
    required: true
  job:
    description: 'Name of the check'
    required: true
  workflow:
    description: 'Name of the workflow'
    required: true
  run_id:
    description: 'Id of the run'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        number: ${{ inputs.pr_number }}
        job: ${{ inputs.job }}
        workflow: ${{ inputs.workflow }}
        details_url: "Details [here](https://github.com/LukeMathWalker/pavex/actions/runs/${{ inputs.run_id }})"
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          const { data: pull } = await github.rest.pulls.get({
            ...context.repo,
            pull_number: process.env.number
          });
          const ref = pull.head.sha;
          const { data: result } = await github.rest.checks.create({
            ...context.repo,
            head_sha: ref,
            name: process.env.job,
            status: 'in_progress',
            output: {
              title: process.env.workflow,
              summary: process.env.details_url
            }
          });
          
          return result;