description = """
Pavex handles types whose generic parameter are not defined in the same crate 
that defines the base type
"""

[expectations]
codegen = "pass"

[dependencies]
hyper = "1.0.0-rc.4"
bytes = "1"

[ephemeral_dependencies]
dep_1 = { path = "dep_1.rs", package = "dep", version = "1.0.0" }
