[package]
name = "in_memory_sessions_server_sdk"
version = "0.1.0"
edition = "2024"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "in_memory_sessions"

[package.metadata.px.verify]
verifier_type = "cargo_workspace_binary"
verifier_name = "in_memory_sessions"
verifier_args = ["--check"]

[dependencies]
biscotti = { version = "0.4", default-features = false }
http = { version = "1", default-features = false }
hyper = { version = "1", default-features = false }
matchit = { version = "0.8", default-features = false }
pavex = { version = "0.2", path = "../../../../../libs/pavex", default-features = false }
pavex_session = { version = "0.2", path = "../../../../../libs/pavex_session", default-features = false }
pavex_session_memory_store = { version = "0.2", path = "../../../../../libs/pavex_session_memory_store", default-features = false }
serde = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }
