//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
#[allow(unused_imports)]
use std as alloc;
struct ServerState {
    router: matchit::Router<u32>,
    application_state: ApplicationState,
}
pub struct ApplicationState {
    s0: sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
    s1: jsonwebtoken::EncodingKey,
}
#[derive(Debug, thiserror::Error)]
pub enum ApplicationStateError {
    #[error(transparent)]
    EncodingKey(jsonwebtoken::errors::Error),
    #[error(transparent)]
    GetPool(sqlx_core::Error),
}
pub async fn build_application_state(
    v0: &conduit_core::configuration::AuthConfig,
    v1: &conduit_core::configuration::DatabaseConfig,
) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
    let v2 = conduit_core::configuration::AuthConfig::encoding_key(v0);
    let v3 = match v2 {
        Ok(ok) => ok,
        Err(v3) => {
            return {
                let v4 = crate::ApplicationStateError::EncodingKey(v3);
                core::result::Result::Err(v4)
            };
        }
    };
    let v4 = conduit_core::configuration::DatabaseConfig::get_pool(v1).await;
    let v5 = match v4 {
        Ok(ok) => ok,
        Err(v5) => {
            return {
                let v6 = crate::ApplicationStateError::GetPool(v5);
                core::result::Result::Err(v6)
            };
        }
    };
    let v6 = crate::ApplicationState {
        s0: v5,
        s1: v3,
    };
    core::result::Result::Ok(v6)
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    let server_state = std::sync::Arc::new(ServerState {
        router: build_router(),
        application_state,
    });
    server_builder.serve(route_request, server_state)
}
fn build_router() -> matchit::Router<u32> {
    let mut router = matchit::Router::new();
    router.insert("/api/ping", 0u32).unwrap();
    router.insert("/articles", 1u32).unwrap();
    router.insert("/articles/:slug", 2u32).unwrap();
    router.insert("/articles/:slug/comments", 3u32).unwrap();
    router.insert("/articles/:slug/comments/:comment_id", 4u32).unwrap();
    router.insert("/articles/:slug/favorite", 5u32).unwrap();
    router.insert("/articles/feed", 6u32).unwrap();
    router.insert("/profiles/:username", 7u32).unwrap();
    router.insert("/profiles/:username/follow", 8u32).unwrap();
    router.insert("/tags", 9u32).unwrap();
    router.insert("/user", 10u32).unwrap();
    router.insert("/users", 11u32).unwrap();
    router.insert("/users/login", 12u32).unwrap();
    router
}
async fn route_request(
    request: http::Request<hyper::body::Incoming>,
    server_state: std::sync::Arc<ServerState>,
) -> pavex::response::Response {
    let (request_head, request_body) = request.into_parts();
    #[allow(unused)]
    let request_body = pavex::request::body::RawIncomingBody::from(request_body);
    let request_head: pavex::request::RequestHead = request_head.into();
    let matched_route = match server_state.router.at(&request_head.uri.path()) {
        Ok(m) => m,
        Err(_) => {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "*",
            );
            return route_2::middleware_0(
                    matched_route_template,
                    &allowed_methods,
                    &request_head,
                )
                .await;
        }
    };
    let route_id = matched_route.value;
    #[allow(unused)]
    let url_params: pavex::request::route::RawRouteParams<'_, '_> = matched_route
        .params
        .into();
    match route_id {
        0u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/api/ping",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_0::middleware_0(matched_route_template, &request_head).await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        1u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_10::middleware_0(matched_route_template, &request_head).await
                }
                &pavex::http::Method::POST => {
                    route_11::middleware_0(
                            matched_route_template,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        2u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles/:slug",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_13::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::DELETE => {
                    route_14::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::PUT => {
                    route_15::middleware_0(
                            matched_route_template,
                            url_params,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                            pavex::http::Method::DELETE,
                            pavex::http::Method::PUT,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        3u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles/:slug/comments",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_18::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::POST => {
                    route_19::middleware_0(
                            matched_route_template,
                            url_params,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        4u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles/:slug/comments/:comment_id",
            );
            match &request_head.method {
                &pavex::http::Method::DELETE => {
                    route_20::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::DELETE,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        5u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles/:slug/favorite",
            );
            match &request_head.method {
                &pavex::http::Method::DELETE => {
                    route_16::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::POST => {
                    route_17::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::DELETE,
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        6u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/articles/feed",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_12::middleware_0(matched_route_template, &request_head).await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        7u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/profiles/:username",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_7::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        8u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/profiles/:username/follow",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_8::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                &pavex::http::Method::DELETE => {
                    route_9::middleware_0(
                            matched_route_template,
                            url_params,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                            pavex::http::Method::DELETE,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        9u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/tags",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_1::middleware_0(matched_route_template, &request_head).await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        10u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/user",
            );
            match &request_head.method {
                &pavex::http::Method::GET => {
                    route_5::middleware_0(matched_route_template, &request_head).await
                }
                &pavex::http::Method::PUT => {
                    route_6::middleware_0(
                            matched_route_template,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::GET,
                            pavex::http::Method::PUT,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        11u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/users",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_3::middleware_0(
                            matched_route_template,
                            &server_state.application_state.s0,
                            &server_state.application_state.s1,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        12u32 => {
            let matched_route_template = pavex::request::route::MatchedRouteTemplate::new(
                "/users/login",
            );
            match &request_head.method {
                &pavex::http::Method::POST => {
                    route_4::middleware_0(
                            matched_route_template,
                            &server_state.application_state.s0,
                            &server_state.application_state.s1,
                            request_body,
                            &request_head,
                        )
                        .await
                }
                _ => {
                    let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                            pavex::http::Method::POST,
                        ])
                        .into();
                    route_2::middleware_0(
                            matched_route_template,
                            &allowed_methods,
                            &request_head,
                        )
                        .await
                }
            }
        }
        i => unreachable!("Unknown route id: {}", i),
    }
}
pub mod route_0 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = conduit_core::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_0::Next0 {
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        conduit_core::telemetry::logger(v4, v2).await
    }
    pub async fn handler() -> pavex::response::Response {
        let v0 = conduit_core::routes::status::ping();
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v0)
    }
    pub struct Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        next: fn() -> T,
    }
    impl<T> std::future::IntoFuture for Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)()
        }
    }
}
pub mod route_1 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = conduit_core::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_1::Next0 {
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        conduit_core::telemetry::logger(v4, v2).await
    }
    pub async fn handler() -> pavex::response::Response {
        let v0 = conduit_core::routes::tags::get_tags();
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v0)
    }
    pub struct Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        next: fn() -> T,
    }
    impl<T> std::future::IntoFuture for Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)()
        }
    }
}
pub mod route_2 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::router::AllowedMethods,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_2::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: &pavex::router::AllowedMethods,
    ) -> pavex::response::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::response::Response as pavex::response::IntoResponse>::into_response(v1)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::router::AllowedMethods,
        next: fn(&'a pavex::router::AllowedMethods) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_3 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        v2: &jsonwebtoken::EncodingKey,
        v3: pavex::request::body::RawIncomingBody,
        v4: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v5 = conduit_core::telemetry::RootSpan::new(v4, v0);
        let v6 = crate::route_3::Next0 {
            s_0: v1,
            s_1: v4,
            s_2: v3,
            s_3: v2,
            next: handler,
        };
        let v7 = pavex::middleware::Next::new(v6);
        conduit_core::telemetry::logger(v7, v5).await
    }
    pub async fn handler(
        v0: &sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        v1: &pavex::request::RequestHead,
        v2: pavex::request::body::RawIncomingBody,
        v3: &jsonwebtoken::EncodingKey,
    ) -> pavex::response::Response {
        let v4 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v5 = pavex::request::body::BufferedBody::extract(v1, v2, v4).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v6,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v7)
                };
            }
        };
        let v7 = pavex::request::body::JsonBody::extract(v1, &v6);
        let v8 = match v7 {
            Ok(ok) => ok,
            Err(v8) => {
                return {
                    let v9 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v8,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v9)
                };
            }
        };
        let v9 = conduit_core::routes::users::signup(v8, v0, v3).await;
        let v10 = match v9 {
            Ok(ok) => ok,
            Err(v10) => {
                return {
                    let v11 = conduit_core::routes::users::SignupError::into_response(
                        &v10,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v11)
                };
            }
        };
        <pavex::response::Response<
            http_body_util::Full<bytes::Bytes>,
        > as pavex::response::IntoResponse>::into_response(v10)
    }
    pub struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        s_1: &'b pavex::request::RequestHead,
        s_2: pavex::request::body::RawIncomingBody,
        s_3: &'c jsonwebtoken::EncodingKey,
        next: fn(
            &'a sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
            &'b pavex::request::RequestHead,
            pavex::request::body::RawIncomingBody,
            &'c jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
}
pub mod route_4 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        v2: &jsonwebtoken::EncodingKey,
        v3: pavex::request::body::RawIncomingBody,
        v4: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v5 = conduit_core::telemetry::RootSpan::new(v4, v0);
        let v6 = crate::route_4::Next0 {
            s_0: v1,
            s_1: v4,
            s_2: v3,
            s_3: v2,
            next: handler,
        };
        let v7 = pavex::middleware::Next::new(v6);
        conduit_core::telemetry::logger(v7, v5).await
    }
    pub async fn handler(
        v0: &sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        v1: &pavex::request::RequestHead,
        v2: pavex::request::body::RawIncomingBody,
        v3: &jsonwebtoken::EncodingKey,
    ) -> pavex::response::Response {
        let v4 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v5 = pavex::request::body::BufferedBody::extract(v1, v2, v4).await;
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v6,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v7)
                };
            }
        };
        let v7 = pavex::request::body::JsonBody::extract(v1, &v6);
        let v8 = match v7 {
            Ok(ok) => ok,
            Err(v8) => {
                return {
                    let v9 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v8,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v9)
                };
            }
        };
        let v9 = conduit_core::routes::users::login(v8, v0, v3).await;
        let v10 = match v9 {
            Ok(ok) => ok,
            Err(v10) => {
                return {
                    let v11 = conduit_core::routes::users::LoginError::into_response(
                        &v10,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v11)
                };
            }
        };
        <pavex::response::Response<
            http_body_util::Full<bytes::Bytes>,
        > as pavex::response::IntoResponse>::into_response(v10)
    }
    pub struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
        s_1: &'b pavex::request::RequestHead,
        s_2: pavex::request::body::RawIncomingBody,
        s_3: &'c jsonwebtoken::EncodingKey,
        next: fn(
            &'a sqlx_core::driver_prelude::pool::Pool<sqlx_postgres::Postgres>,
            &'b pavex::request::RequestHead,
            pavex::request::body::RawIncomingBody,
            &'c jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3)
        }
    }
}
pub mod route_5 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = conduit_core::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_5::Next0 {
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        conduit_core::telemetry::logger(v4, v2).await
    }
    pub async fn handler() -> pavex::response::Response {
        let v0 = conduit_core::routes::users::get_user();
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v0)
    }
    pub struct Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        next: fn() -> T,
    }
    impl<T> std::future::IntoFuture for Next0<T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)()
        }
    }
}
pub mod route_6 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_6::Next0 {
            s_0: v1,
            s_1: v2,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v3 = pavex::request::body::BufferedBody::extract(v1, v0, v2).await;
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v4,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v5)
                };
            }
        };
        let v5 = pavex::request::body::JsonBody::extract(v1, &v4);
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v6,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v7)
                };
            }
        };
        let v7 = conduit_core::routes::users::update_user(v6);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v7)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1)
        }
    }
}
pub mod route_7 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_7::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::profiles::get_profile(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_8 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_8::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::profiles::follow_profile(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_9 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_9::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::profiles::unfollow_profile(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_10 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = conduit_core::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_10::Next0 {
            s_0: v1,
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        conduit_core::telemetry::logger(v4, v2).await
    }
    pub async fn handler(v0: &pavex::request::RequestHead) -> pavex::response::Response {
        let v1 = pavex::request::query::QueryParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::query::errors::ExtractQueryParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::list_articles(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::request::RequestHead,
        next: fn(&'a pavex::request::RequestHead) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_11 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_11::Next0 {
            s_0: v1,
            s_1: v2,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v3 = pavex::request::body::BufferedBody::extract(v1, v0, v2).await;
        let v4 = match v3 {
            Ok(ok) => ok,
            Err(v4) => {
                return {
                    let v5 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v4,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v5)
                };
            }
        };
        let v5 = pavex::request::body::JsonBody::extract(v1, &v4);
        let v6 = match v5 {
            Ok(ok) => ok,
            Err(v6) => {
                return {
                    let v7 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v6,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v7)
                };
            }
        };
        let v7 = conduit_core::routes::articles::publish_article(v6);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v7)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1)
        }
    }
}
pub mod route_12 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v2 = conduit_core::telemetry::RootSpan::new(v1, v0);
        let v3 = crate::route_12::Next0 {
            s_0: v1,
            next: handler,
        };
        let v4 = pavex::middleware::Next::new(v3);
        conduit_core::telemetry::logger(v4, v2).await
    }
    pub async fn handler(v0: &pavex::request::RequestHead) -> pavex::response::Response {
        let v1 = pavex::request::query::QueryParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::query::errors::ExtractQueryParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::get_feed(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: &'a pavex::request::RequestHead,
        next: fn(&'a pavex::request::RequestHead) -> T,
    }
    impl<'a, T> std::future::IntoFuture for Next0<'a, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_13 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_13::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::get_article(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_14 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_14::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::delete_article(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_15 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: pavex::request::body::RawIncomingBody,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = conduit_core::telemetry::RootSpan::new(v3, v0);
        let v5 = crate::route_15::Next0 {
            s_0: v2,
            s_1: v1,
            s_2: v3,
            next: handler,
        };
        let v6 = pavex::middleware::Next::new(v5);
        conduit_core::telemetry::logger(v6, v4).await
    }
    pub async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v4 = pavex::request::body::BufferedBody::extract(v2, v0, v3).await;
        let v5 = match v4 {
            Ok(ok) => ok,
            Err(v5) => {
                return {
                    let v6 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v5,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v6)
                };
            }
        };
        let v6 = pavex::request::body::JsonBody::extract(v2, &v5);
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v7,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::route::RouteParams::extract(v1);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v9,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = conduit_core::routes::articles::update_article(v9, v7);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v10)
    }
    pub struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: pavex::request::route::RawRouteParams<'a, 'b>,
        s_2: &'c pavex::request::RequestHead,
        next: fn(
            pavex::request::body::RawIncomingBody,
            pavex::request::route::RawRouteParams<'a, 'b>,
            &'c pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
}
pub mod route_16 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_16::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::unfavorite_article(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_17 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_17::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::favorite_article(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_18 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_18::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::list_comments(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
pub mod route_19 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: pavex::request::body::RawIncomingBody,
        v3: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v4 = conduit_core::telemetry::RootSpan::new(v3, v0);
        let v5 = crate::route_19::Next0 {
            s_0: v2,
            s_1: v1,
            s_2: v3,
            next: handler,
        };
        let v6 = pavex::middleware::Next::new(v5);
        conduit_core::telemetry::logger(v6, v4).await
    }
    pub async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = <pavex::request::body::BodySizeLimit as std::default::Default>::default();
        let v4 = pavex::request::body::BufferedBody::extract(v2, v0, v3).await;
        let v5 = match v4 {
            Ok(ok) => ok,
            Err(v5) => {
                return {
                    let v6 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v5,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v6)
                };
            }
        };
        let v6 = pavex::request::body::JsonBody::extract(v2, &v5);
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v7,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::route::RouteParams::extract(v1);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v9,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = conduit_core::routes::articles::publish_comment(v9, v7);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v10)
    }
    pub struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: pavex::request::route::RawRouteParams<'a, 'b>,
        s_2: &'c pavex::request::RequestHead,
        next: fn(
            pavex::request::body::RawIncomingBody,
            pavex::request::route::RawRouteParams<'a, 'b>,
            &'c pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
}
pub mod route_20 {
    pub async fn middleware_0(
        v0: pavex::request::route::MatchedRouteTemplate,
        v1: pavex::request::route::RawRouteParams<'_, '_>,
        v2: &pavex::request::RequestHead,
    ) -> pavex::response::Response {
        let v3 = conduit_core::telemetry::RootSpan::new(v2, v0);
        let v4 = crate::route_20::Next0 {
            s_0: v1,
            next: handler,
        };
        let v5 = pavex::middleware::Next::new(v4);
        conduit_core::telemetry::logger(v5, v3).await
    }
    pub async fn handler(
        v0: pavex::request::route::RawRouteParams<'_, '_>,
    ) -> pavex::response::Response {
        let v1 = pavex::request::route::RouteParams::extract(v0);
        let v2 = match v1 {
            Ok(ok) => ok,
            Err(v2) => {
                return {
                    let v3 = pavex::request::route::errors::ExtractRouteParamsError::into_response(
                        &v2,
                    );
                    <pavex::response::Response<
                        http_body_util::Full<bytes::Bytes>,
                    > as pavex::response::IntoResponse>::into_response(v3)
                };
            }
        };
        let v3 = conduit_core::routes::articles::delete_comment(v2);
        <http::StatusCode as pavex::response::IntoResponse>::into_response(v3)
    }
    pub struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        s_0: pavex::request::route::RawRouteParams<'a, 'b>,
        next: fn(pavex::request::route::RawRouteParams<'a, 'b>) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::response::Response>,
    {
        type Output = pavex::response::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0)
        }
    }
}
