[package]
name = "session_installation_sqlite"
version = "0.1.0"
edition = "2021"


[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(pavex_ide_hint)'] }

[dependencies]
pavex = { path = "../../../../../libs/pavex" }
pavex_session = { path = "../../../../../libs/pavex_session" }
pavex_session_sqlx = { path = "../../../../../libs/pavex_session_sqlx", features = [
    "sqlite",
] }
pavex_cli_client = { path = "../../../../../libs/pavex_cli_client" }
serde = { version = "1", features = ["derive"] }
cargo_px_env = "0.1"
tokio = { version = "1.35.1", features = ["time"] }
anyhow = "1"
sqlx = { version = "0.8", default-features = false, features = [
    "sqlite",
    "runtime-tokio-rustls",
] }

[workspace]
members = [".", "server_sdk"]
