name: CI freshness

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-freshness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: Generate docs.yml
        run: |
          cd .github/ci_generator
          cargo run > docs.yml
          mv docs.yml ../workflows
      - name: Fail if anything changed
        run: |
          git add .
          git diff --exit-code --cached || (echo "Please regenerate the docs.yml CI script" && exit 1)
