name: Re-enable workspace hack after a release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # Check https://docs.rs/cargo-hakari/0.9.29/cargo_hakari/#installation
      # to learn how to install cargo-hakari locally
      - name: Install cargo-hakari
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hakari
      - name: Set git identity
        run: |
          git config --global user.name "pavex-releaser[bot]"
          git config --global user.email "ci@pavex.dev"
      - name: Re-enable workspace hack
        run: |
          cd libs
          cargo hakari generate
          cargo hakari manage-deps --yes
          git add .
          git commit -am "Re-enable workspace hack after a release"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch-suffix: "random"
          title: "Re-enable workspace hack after a release"
