name: "Publish crates to crates.io"

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, join('chore', ':', ' release')) }}
    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set git identity
        run: |
          git config --global user.name "pavex-releaser[bot]"
          git config --global user.email "ci@pavex.dev"
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: "release"
          project_manifest: "libs/Cargo.toml"
          config: "libs/.release-plz.toml"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
